### ISSUE TITLE
Code availability for generating OOD matrices

### ISSUE THREAD

**Issue by hugy718** [intel/ScalableVectorSearch#53]
Thank you for making the codes publicly available. Are the codes for generating the OOD data and query matrices released somewhere else? It seems that the tests in this repo used pre-generated matrices.

**Comment by ibhati** [comment]
Thanks for your interest in our library. The leanvec OOD matrices can be computed using the scripts provided here: 
https://github.com/intel/ScalableVectorSearch/blob/main/bindings/python/src/svs/leanvec.py#L41

An example of these calls can be found in one of the tests here: https://github.com/intel/ScalableVectorSearch/blob/main/bindings/python/tests/test_vamana.py#L69
