### ISSUE TITLE
Compilation Issues with Scalable Vector Search

### ISSUE THREAD

**Issue by ssd-mry** [intel/ScalableVectorSearch#57]
Hello,

I'm trying to run the Scalable Vector Search project after reading your paper "Similarity search in the blink of an eye with compressed indices." I'm very interested in exploring this further. However, I encountered several compilation errors.

Here are the key errors I faced:

1. ‘any_of’ is not a member of ‘std’: I ensured C++20 is set, but the error persists.
2. Forming reference to void in value.hpp: This seems to be linked to the types being used.
3. Static assertion failed: The compilation fails with a static assertion that requires a TOML value to be one of the native types, but I'm passing a unique pointer, which is causing the issue.
![image](https://github.com/user-attachments/assets/22e329c6-6075-4173-9c9d-d9007f15ebd5)
![image](https://github.com/user-attachments/assets/0ca1b0df-cf1a-42dc-9b64-858fdb7b297f)

Environment:
CentOS，GCC 14.2.0，toml++-3.4.0

I would appreciate any guidance or suggestions you could provide to help resolve these issues.

Thank you!

Thank you!

**Comment by mihaic** [comment]
Are you still having compilation issues, @ssd-mry? Were you able to try the setup I suggested?

**Comment by mihaic** [comment]
Feel free to reopen the issue if you are still having trouble.
