### ISSUE TITLE
What is the meaning of x in the Equation 6?

### ISSUE THREAD

**Issue by jiyangbai** [intel/ScalableVectorSearch#58]
Hello, what is the meaning of x in the Equation 6? I did not find its definition in the paper. Thanks!

**Comment by aguerreb** [comment]
Thanks for your interest in our work! I assume you’re referring to Eq. (6) in our paper "Similarity search in the blink of an eye with compressed indices". The variable x in that equation refers to the residual r (which is defined in the paragraph right before the equation), so it should actually be: Q_res(r; B') = Q(r; B', -delta/2, delta/2).
